
export const LOAD_VIDEO_DATA_SUCCESS = 'LOAD_VIDEO_DATA_SUCCESS';
export const LOAD_CHANNEL_DATA_SUCCESS = 'LOAD_CHANNEL_DATA_SUCCESS';
export const LOAD_COMMENTS_DATA_SUCCESS = 'LOADA_COMMENTS_DATA_SUCCESS';

export const LOAD_VIDEO_DATA_FAILED = 'LOAD_VIDEO_DATA_FAILED';
export const LOAD_CHANNEL_DATA_FAILED = 'LOAD_CHANNEL_DATA_FAILED';
export const LOADA_COMMENTS_DATA_FAILED = 'LOADA_COMMENTS_DATA_FAILED';